apiVersion: v1
kind: Service
metadata:
  name: dkom-k8s
  namespace: dkom
spec:
  ports:
  - port: 80
    targetPort: 1337 
    protocol: TCP
    name: dkom-k8s
  type: LoadBalancer
  selector:
    app: dkom-k8s 